---
output: pdf_document
---

## Woodward Family Scottish Shortbread
## From the kitchens of Mary Woodward and Bette Stephens 


This recipe has been handed down, and expanded on for over 150 years – through more than 7 generations. 
Our tradition was to gift these to family and friends before Christmas.  

### Makes approximately 24 cookies  

## Ingredients for cookies
* 1 lb plus 1 tablespoon unsalted European butter, softened (I use KerryGold Irish unsalted butter (buy at Costco); Plugra also works or any French or Belgian or UK butter)
* 1 cup superfine sugar (I use King Arthur's Special Bakers sugar from kingarthurflour.com ; alternately can use C&H cane confectioners sugar from the grocery store)
* 5 cups pastry flour, measure after sifting (I use King Arthur's Pastry flour; alternatively can use King Arthur's all purpose flour (can find in some grocery stores))
parchment paper or shortbread molds
* Optional ingredients for decorating cookies
+	sliced almonds
+	Swedish pearl sugar (available from	kingarthurflour.com or in Ballard)
+	Heavy cream (a few Tablespoons)
+	Scharffen Berger or Valharona semisweet baking chunks


## Directions for making cookies
*	Preheat oven to 350 degrees. Cover cookie sheets with parchment paper. If using shortbread molds, brush lightly with unsalted butter.
*	With heavy electric mixer (Kitchenaid or commercial), beat 1 lb of softened butter and 1 cup of superfine sugar at high speed until mixture is light and fluffy.
*	Reduce speed to medium and beat in sifted flour, 1 cup at a time; continue beating until smooth.
*	If dough becomes too stiff to stir, knead in the remaining flour by hand
*	On lightly floured surface, roll 1/2 the dough into a rectangle about 10" long by 8" wide by 1/2" high. 
*	TRADITIONAL - using a ruler and small sharp knife (or pastry wheel) cut the rectangle lengthwise into four 2" strips.. Make crisscross diagonal cuts at about 21/2" intervals to form small triangles. Use a fork to prick surface into a pretty pattern of tiny holes on the surface. Cookies will almost double in size when baked.
*	Arrange the triangles on the baking sheet and bake in the middle of the oven for 25 to 30 minutes until firm to touch and slightly brown. 
* With a metal spatula, move to a cake rack to cool completely.
*	Before reusing your cookie sheet to bake more cookies, be certain that it is completely cool. Can reuse the parchment paper
*	Will keep for 2 to 3 weeks in tightly covers jars or tins.

## Alternative Shapes for Shortbread
1. Shape into small logs, brush with cream, coat in a Swedish pearl sugar and chopped almond mix. Then bake as above
2. If using a shortbread pan, will take 35-40 minutes to bake
3. Shape like small horseshoes, brush with cream, coat in chopped nuts
4. After cool, dip 1/2 of the cookie into melted baking chocolate then refrigerate until chocolate is set. Can also add nuts if wanted.
5. Cut into small rectangles instead of triangles. May take less time to bake.
6. Shape into mouse shape, use sliced almonds for ears, then bake. When slightly cooled, insert licorice ropes (usually from Sweden or Norway) for tails and cut bits for eyes and nose.
7. Use as pie crust for tarts.  Once cooked fill with curd (see recipe elsewhere in this document) and sprinkle with sliced or chopped nuts and pearl sugar

## The original recipe from the 1800’s (passed down orally)
* Churn 2 cups of butter from Guernsey cows
* Finely grind 1 cup of sugar
* Finely grind 5 cups of wheat into flour
1. With a strong hand, blend the butter and sugar then stir in 1 cup of flour at a time
2. Bring in enough wood to constantly stoke the oven so that it remains at 175 degrees celcius
3. Roll dough evenly to 1 centimeter. Cut into triangles and place on cookie sheet. Poke each cookie with the tines of a fork.
4. Cook for 25 – 30 minutes until firm but not brown
5. Cool on racks.  Can be stored in tins up to one month